import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import styled from "styled-components";
import './reset.css'
import './main.css'
// import {HeaderBanner} from "@components/molecules";
// import {Features} from "@components/organizms/Features.tsx";
// import {Contacts} from "@components/organizms/Contacts.tsx";
// import {LegalInformation} from "@components/organizms";
// import {FeaturesList} from "@components/organizms/FeaturesList.tsx";
import {useJson} from "../utils";
// import {Outlet} from "react-router";

const inter = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const MainContainer = styled.div({
  display: 'flex',
  flexDirection: 'column',
  alignItems: 'center',
  paddingBottom: '20px'
})

const Content = styled.div({
  padding: '0 5%',
  width: '100%'
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const response = useJson()
  return (
    <html lang="en">
      <body className={inter.className}>
      <div>ПИСЬКА</div>{children}</body>
    </html>
    
    // <MainContainer>
    //         <HeaderBanner/>
    //         <Content>
    //             <FeaturesList/>
    //             <Features response={response}/>
    //             <Contacts/>
    //             <LegalInformation/>
    //             <Outlet/>
    //         </Content>
    //     </MainContainer>
  );
}
